### PR TITLE
Fix sceptre_user_data recursion error

### PR DESCRIPTION
**Pull request by ScOut3R**
Fix for https://github.com/cloudreach/sceptre/issues/558

See https://github.com/michaetto/sceptre/commit/874f5e5bbc027dfee43e3128878cbf15ed33b4da

### CODE REVIEW

**Comment by zaro0508** [comment]
Thanks @ScOut3R.  I've verified that this works with @ngfgrant at https://github.com/cloudreach/sceptre/commit/65d6896a7aa1d5af55018f4688a8ce4614bc47da

Just waiting for his that fix to be released before merging this update.

**Comment by ScOut3R** [comment]
@zaro0508 I've seen that a new release was published with which includes #696.

I've installed version 2.1.2 of Sceptre and the master branch of this repository yet I am still getting the recursion depth error when using the ssm resolver.

Did you have any chance of testing the upstream changes?

**Comment by ngfgrant** [comment]
@ScOut3R are you able to share the project or example of the project? What other resolvers are you using?

**Comment by zaro0508** [comment]
@ScOut3R I have not merged this change to master yet.

**Comment by ScOut3R** [comment]
@zaro0508 I am sorry, I misread your initial comment. I thought that the upstream fix will be enough for this resolver.

As I understand now you still have to apply a fix to this project to resolve the issue.

**Pull request merged**
